### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by thonythony** [bucharest-gold/opossum#181] opened 2018-04-11 15:05 UTC
**Node.js Version:**
node v8.9.4
**Operating System:**
Linux 4.14.0-deepin2-amd64 #1 SMP PREEMPT Deepin 4.14.12-2 (2018-01-06) x86_64 GNU/Linux

**Steps to Produce Error:**
I have a component A that calls a component B using an http request.
When I benchmark this action using ab, without opossum, the average time per request is 50ms.
When I **wrap the http request into opossum** and I benchmark this action with ab, the average time per request **increases exponentially after each request** and errors are printed to console : 
```
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 unpipe listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 close listeners added. Use emitter.setMaxListeners() to increase limit
(node:25619) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

The ab command I use :
```
ab -n 10000 -c 100 http://localhost:3000/check1
```

Can you help me please ?

**Comment by lance** [comment] 2018-04-11 19:52
@thonythony do you experience this issue if you downgrade to version 1.3.1?

**Comment by helio-frota** [comment] 2018-04-11 20:15
@thonythony I could not reproduce.

Here a POC with the results:
https://github.com/helio-frota/opc

**Comment by thonythony** [comment] 2018-04-12 09:57
Hello,

@lance yes we tested with 1.3 and 1.4

@helio-frota thanks for your poc, I tested it and it works perfectly !

I see ours implementations differ. Unlike you, In my tests I instantiate a new circuit breaker instance for each request made. I think the memory leak and performance issues occur when a lot of circuit breaker are instantiated. 
We will change our code and implement a singleton service. I will keep you informed.

**Comment by lance** [comment] 2018-04-18 13:33
Thanks for the followup @thonthony  - I'm going to close this for now. If something else comes up related to it, please feel free to reopen or create a new issue.

**Closed** 2018-04-18 13:34 UTC
Labels: review

**Comment by dptoot** [comment] 2020-01-26 17:38
@helio-frota Is there anyway to resurrect or elaborate on the pattern demonstrated here

https://github.com/helio-frota/opc

We are seeing performance issues and I believe we have fallen into the same trap @thonythony did and attached a circuit breaker per request.  Is the idea to generate som sort of Circuit Breaker manager class or singleton that keeps track of previously established breakers and returns them if they are requested again?  That is how we are thinking of tackling this but wanted to be sure,  If so do we think this might need to be added to the docs?  I would be happy to add them.

**Comment by helio-frota** [comment] 2020-01-30 12:41
@dptoot hi, sorry I don't recall exactly what I did on that :neutral_face:, my priorities/tasks were changed over the time and lot of things changed on opossum during that period.
